name: Execucio Diaria Patu-Bot Nou Patufet

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

# AFEGIM AIXÒ PER FER DESAPARÈIXER EL WARNING DE NODE.JS 20
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codi del repositori
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: true

      - name: Configurar Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.12'

      - name: Instal·lar llibreries necessaries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar el Patu-Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: python monitor_subvencions.py

      - name: Guardar historial de duplicats
        run: |
          git config --global user.name "Patu-bot"
          git config --global user.email "bot@noupatufet.cat"
          git add historial_subvencions.json || true
          if git diff --staged --quiet; then
            echo "Sense canvis a l'historial."
          else
            git commit -m "Actualització historial (9:00 AM) [skip ci]"
            git push
          fi
